callback_monitor: val/PCK

data: ../_base_/data/keypoint_detection.yaml

overrides:
  reset:
    - data.train_subset.augmentations_cpu
    - data.val_subset.augmentations_cpu
    - data.test_subset.augmentations_cpu

  data:
    stack_images: false
    train_subset:
      augmentations_cpu:
        - class_path: torchvision.transforms.v2.ToImage
    val_subset:
      augmentations_cpu:
        - class_path: torchvision.transforms.v2.ToImage
    test_subset:
      batch_size: 64
      augmentations_cpu:
        - class_path: torchvision.transforms.v2.ToImage
