callback_monitor: val/PCK

data: ../_base_/data/keypoint_detection.yaml

overrides:
  reset:
    - data.train_subset.augmentations_cpu
    - data.train_subset.augmentations_gpu
    - data.test_subset.augmentations_cpu

  data:
    train_subset:
      augmentations_cpu:
        - class_path: getitune.data.augmentation.transforms.Resize
          init_args:
            size: $(input_size)
            keep_aspect_ratio: false
      augmentations_gpu: []
    test_subset:
      batch_size: 64
      augmentations_cpu:
        - class_path: getitune.data.augmentation.transforms.Resize
          init_args:
            size: $(input_size)
            keep_aspect_ratio: false
            resize_targets: false
      augmentations_gpu: []
