/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/api/models': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Models
         * @description Get information about available models
         */
        get: operations['get_models_api_models_get'];
        put?: never;
        /**
         * Add Model
         * @description Upload a new model
         */
        post: operations['add_model_api_models_post'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/models/{model_name}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Model
         * @description Delete a model
         */
        delete: operations['delete_model_api_models__model_name__delete'];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/models/{model_name}:activate': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Activate Model
         * @description Activate a model
         */
        post: operations['activate_model_api_models__model_name__activate_post'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/input_hook': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**   */
        post: operations['__api_input_hook_post'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/predictions': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Updates */
        get: operations['stream_updates_api_predictions_get'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/predictions/latest': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest Updates */
        get: operations['latest_updates_api_predictions_latest_get'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/webrtc/offer': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Offer
         * @description Handle an incoming WebRTC offer via HTTP POST.
         *
         *     Processes the SDP offer and ICE candidates from the client to establish
         *     a WebRTC connection.
         *
         *     Args:
         *         body: A Pydantic model containing the SDP offer, optional ICE candidate,
         *               type ('offer'), and a unique WebRTC ID.
         *
         *     Returns:
         *         A dictionary containing the SDP answer generated by the server.
         */
        post: operations['offer_api_webrtc_offer_post'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/telephone/incoming': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Handle Incoming Call
         * @description Handle incoming telephone calls (e.g., via Twilio).
         *
         *     Generates TwiML instructions to connect the incoming call to the
         *     WebSocket handler (`/telephone/handler`) for audio streaming.
         *
         *     Args:
         *         request: The FastAPI Request object for the incoming call webhook.
         *
         *     Returns:
         *         An HTMLResponse containing the TwiML instructions as XML.
         */
        post: operations['handle_incoming_call_api_telephone_incoming_post'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body */
        Body: {
            /** Sdp */
            sdp?: string | null;
            /** Candidate */
            candidate?: {
                [key: string]: unknown;
            } | null;
            /** Type */
            type: string;
            /** Webrtc Id */
            webrtc_id: string;
        };
        /** Body_add_model_api_models_post */
        Body_add_model_api_models_post: {
            /**
             * Xml File
             * Format: binary
             */
            xml_file: string;
            /**
             * Bin File
             * Format: binary
             */
            bin_file: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components['schemas']['ValidationError'][];
        };
        /** InputData */
        InputData: {
            /** Webrtc Id */
            webrtc_id: string;
            /** Conf Threshold */
            conf_threshold: number;
        };
        /** ModelResponse */
        ModelResponse: {
            /** Model Name */
            model_name: string;
        };
        /** ModelsInfoResponse */
        ModelsInfoResponse: {
            /** Active Model */
            active_model: string | null;
            /** Available Models */
            available_models: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type SchemaBody = components['schemas']['Body'];
export type SchemaBodyAddModelApiModelsPost = components['schemas']['Body_add_model_api_models_post'];
export type SchemaHttpValidationError = components['schemas']['HTTPValidationError'];
export type SchemaInputData = components['schemas']['InputData'];
export type SchemaModelResponse = components['schemas']['ModelResponse'];
export type SchemaModelsInfoResponse = components['schemas']['ModelsInfoResponse'];
export type SchemaValidationError = components['schemas']['ValidationError'];
export type $defs = Record<string, never>;
export interface operations {
    get_models_api_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ModelsInfoResponse'];
                };
            };
        };
    };
    add_model_api_models_post: {
        parameters: {
            query: {
                /** @description Name for the model files */
                model_name: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'multipart/form-data': components['schemas']['Body_add_model_api_models_post'];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ModelResponse'];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['HTTPValidationError'];
                };
            };
        };
    };
    delete_model_api_models__model_name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['HTTPValidationError'];
                };
            };
        };
    };
    activate_model_api_models__model_name__activate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ModelResponse'];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['HTTPValidationError'];
                };
            };
        };
    };
    __api_input_hook_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['InputData'];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['HTTPValidationError'];
                };
            };
        };
    };
    stream_updates_api_predictions_get: {
        parameters: {
            query: {
                webrtc_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['HTTPValidationError'];
                };
            };
        };
    };
    latest_updates_api_predictions_latest_get: {
        parameters: {
            query: {
                webrtc_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['HTTPValidationError'];
                };
            };
        };
    };
    offer_api_webrtc_offer_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['Body'];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['HTTPValidationError'];
                };
            };
        };
    };
    handle_incoming_call_api_telephone_incoming_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': unknown;
                };
            };
        };
    };
}
