/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/api/models': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Models
         * @description Get information about available models
         */
        get: operations['get_models_api_models_get'];
        put?: never;
        /**
         * Add Model
         * @description Upload a new model
         */
        post: operations['add_model_api_models_post'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/models/{model_name}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Model
         * @description Delete a model
         */
        delete: operations['delete_model_api_models__model_name__delete'];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/models/{model_name}:activate': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Activate Model
         * @description Activate a model
         */
        post: operations['activate_model_api_models__model_name__activate_post'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/inputs': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Input Configuration
         * @description Get the current input stream configuration.
         */
        get: operations['get_input_configuration_api_inputs_get'];
        put?: never;
        /**
         * Configure Input Stream
         * @description Configure the input stream for the application.
         */
        post: operations['configure_input_stream_api_inputs_post'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/outputs': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Output Configurations
         * @description Get the current output configurations.
         */
        get: operations['get_output_configurations_api_outputs_get'];
        put?: never;
        /**
         * Configure Outputs
         * @description Configure the destination(s) for the application output.
         */
        post: operations['configure_outputs_api_outputs_post'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/system/metrics/memory': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Memory
         * @description Returns the used memory in MB and total available memory in MB.
         */
        get: operations['get_memory_api_system_metrics_memory_get'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/docs': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scalar Docs
         * @description Shows docs for our OpenAPI specification using scalar
         */
        get: operations['get_scalar_docs_api_docs_get'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/input_hook': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Webrtc Input Hook
         * @description Update webrtc input for user
         */
        post: operations['webrtc_input_hook_api_input_hook_post'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/webrtc/offer': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Offer
         * @description Handle an incoming WebRTC offer via HTTP POST.
         *
         *     Processes the SDP offer and ICE candidates from the client to establish
         *     a WebRTC connection.
         *
         *     Args:
         *         body: A Pydantic model containing the SDP offer, optional ICE candidate,
         *               type ('offer'), and a unique WebRTC ID.
         *
         *     Returns:
         *         A dictionary containing the SDP answer generated by the server.
         */
        post: operations['offer_api_webrtc_offer_post'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/telephone/incoming': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Handle Incoming Call
         * @description Handle incoming telephone calls (e.g., via Twilio).
         *
         *     Generates TwiML instructions to connect the incoming call to the
         *     WebSocket handler (`/telephone/handler`) for audio streaming.
         *
         *     Args:
         *         request: The FastAPI Request object for the incoming call webhook.
         *
         *     Returns:
         *         An HTMLResponse containing the TwiML instructions as XML.
         */
        post: operations['handle_incoming_call_api_telephone_incoming_post'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body */
        Body: {
            /** Sdp */
            sdp?: string | null;
            /** Candidate */
            candidate?: {
                [key: string]: unknown;
            } | null;
            /** Type */
            type: string;
            /** Webrtc Id */
            webrtc_id: string;
        };
        /** Body_add_model_api_models_post */
        Body_add_model_api_models_post: {
            /**
             * Xml File
             * Format: binary
             */
            xml_file: string;
            /**
             * Bin File
             * Format: binary
             */
            bin_file: string;
        };
        /** DdsOutputConfig */
        DdsOutputConfig: {
            /** Output Formats */
            output_formats: components['schemas']['OutputFormat'][];
            /** Rate Limit */
            rate_limit?: number | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            destination_type: 'dds';
            /** Dds Topic */
            dds_topic: string;
        };
        /** DisconnectedOutputConfig */
        DisconnectedOutputConfig: {
            /** Output Formats */
            output_formats: components['schemas']['OutputFormat'][];
            /** Rate Limit */
            rate_limit?: number | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            destination_type: 'disconnected';
        };
        /** DisconnectedSourceConfig */
        DisconnectedSourceConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            source_type: 'disconnected';
        };
        /** FolderOutputConfig */
        FolderOutputConfig: {
            /** Output Formats */
            output_formats: components['schemas']['OutputFormat'][];
            /** Rate Limit */
            rate_limit?: number | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            destination_type: 'folder';
            /** Folder Path */
            folder_path: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components['schemas']['ValidationError'][];
        };
        /** IPCameraSourceConfig */
        IPCameraSourceConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            source_type: 'ip_camera';
            /** Stream Url */
            stream_url: string;
            /**
             * Auth Required
             * @default false
             */
            auth_required: boolean;
        };
        /** ImagesFolderSourceConfig */
        ImagesFolderSourceConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            source_type: 'images_folder';
            /** Images Folder Path */
            images_folder_path: string;
        };
        /** InputData */
        InputData: {
            /** Webrtc Id */
            webrtc_id: string;
            /** Conf Threshold */
            conf_threshold: number;
        };
        /** ModelResponse */
        ModelResponse: {
            /** Model Name */
            model_name: string;
        };
        /** ModelsInfoResponse */
        ModelsInfoResponse: {
            /** Active Model */
            active_model: string | null;
            /** Available Models */
            available_models: string[];
        };
        /** MqttOutputConfig */
        MqttOutputConfig: {
            /** Output Formats */
            output_formats: components['schemas']['OutputFormat'][];
            /** Rate Limit */
            rate_limit?: number | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            destination_type: 'mqtt';
            /** Broker Host */
            broker_host: string;
            /** Broker Port */
            broker_port: number;
            /** Topic */
            topic: string;
            /** Username */
            username?: string | null;
            /** Password */
            password?: string | null;
        };
        /**
         * OutputFormat
         * @enum {string}
         */
        OutputFormat: 'image_original' | 'image_with_predictions' | 'predictions';
        /** RosOutputConfig */
        RosOutputConfig: {
            /** Output Formats */
            output_formats: components['schemas']['OutputFormat'][];
            /** Rate Limit */
            rate_limit?: number | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            destination_type: 'ros';
            /** Ros Topic */
            ros_topic: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VideoFileSourceConfig */
        VideoFileSourceConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            source_type: 'video_file';
            /** Video Path */
            video_path: string;
        };
        /** WebcamSourceConfig */
        WebcamSourceConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            source_type: 'webcam';
            /** Device Id */
            device_id: number;
        };
        /** WebhookOutputConfig */
        WebhookOutputConfig: {
            /** Output Formats */
            output_formats: components['schemas']['OutputFormat'][];
            /** Rate Limit */
            rate_limit?: number | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            destination_type: 'webhook';
            /** Webhook Url */
            webhook_url: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type SchemaBody = components['schemas']['Body'];
export type SchemaBodyAddModelApiModelsPost = components['schemas']['Body_add_model_api_models_post'];
export type SchemaDdsOutputConfig = components['schemas']['DdsOutputConfig'];
export type SchemaDisconnectedOutputConfig = components['schemas']['DisconnectedOutputConfig'];
export type SchemaDisconnectedSourceConfig = components['schemas']['DisconnectedSourceConfig'];
export type SchemaFolderOutputConfig = components['schemas']['FolderOutputConfig'];
export type SchemaHttpValidationError = components['schemas']['HTTPValidationError'];
export type SchemaIpCameraSourceConfig = components['schemas']['IPCameraSourceConfig'];
export type SchemaImagesFolderSourceConfig = components['schemas']['ImagesFolderSourceConfig'];
export type SchemaInputData = components['schemas']['InputData'];
export type SchemaModelResponse = components['schemas']['ModelResponse'];
export type SchemaModelsInfoResponse = components['schemas']['ModelsInfoResponse'];
export type SchemaMqttOutputConfig = components['schemas']['MqttOutputConfig'];
export type SchemaOutputFormat = components['schemas']['OutputFormat'];
export type SchemaRosOutputConfig = components['schemas']['RosOutputConfig'];
export type SchemaValidationError = components['schemas']['ValidationError'];
export type SchemaVideoFileSourceConfig = components['schemas']['VideoFileSourceConfig'];
export type SchemaWebcamSourceConfig = components['schemas']['WebcamSourceConfig'];
export type SchemaWebhookOutputConfig = components['schemas']['WebhookOutputConfig'];
export type $defs = Record<string, never>;
export interface operations {
    get_models_api_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ModelsInfoResponse'];
                };
            };
        };
    };
    add_model_api_models_post: {
        parameters: {
            query: {
                /** @description Name for the model files */
                model_name: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'multipart/form-data': components['schemas']['Body_add_model_api_models_post'];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ModelResponse'];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['HTTPValidationError'];
                };
            };
        };
    };
    delete_model_api_models__model_name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['HTTPValidationError'];
                };
            };
        };
    };
    activate_model_api_models__model_name__activate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ModelResponse'];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['HTTPValidationError'];
                };
            };
        };
    };
    get_input_configuration_api_inputs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json':
                        | components['schemas']['DisconnectedSourceConfig']
                        | components['schemas']['WebcamSourceConfig']
                        | components['schemas']['IPCameraSourceConfig']
                        | components['schemas']['VideoFileSourceConfig']
                        | components['schemas']['ImagesFolderSourceConfig'];
                };
            };
        };
    };
    configure_input_stream_api_inputs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json':
                    | components['schemas']['DisconnectedSourceConfig']
                    | components['schemas']['WebcamSourceConfig']
                    | components['schemas']['IPCameraSourceConfig']
                    | components['schemas']['VideoFileSourceConfig']
                    | components['schemas']['ImagesFolderSourceConfig'];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['HTTPValidationError'];
                };
            };
        };
    };
    get_output_configurations_api_outputs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': (
                        | components['schemas']['DisconnectedOutputConfig']
                        | components['schemas']['FolderOutputConfig']
                        | components['schemas']['MqttOutputConfig']
                        | components['schemas']['DdsOutputConfig']
                        | components['schemas']['RosOutputConfig']
                        | components['schemas']['WebhookOutputConfig']
                    )[];
                };
            };
        };
    };
    configure_outputs_api_outputs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': (
                    | components['schemas']['DisconnectedOutputConfig']
                    | components['schemas']['FolderOutputConfig']
                    | components['schemas']['MqttOutputConfig']
                    | components['schemas']['DdsOutputConfig']
                    | components['schemas']['RosOutputConfig']
                    | components['schemas']['WebhookOutputConfig']
                )[];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['HTTPValidationError'];
                };
            };
        };
    };
    get_memory_api_system_metrics_memory_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_scalar_docs_api_docs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': unknown;
                };
            };
        };
    };
    webrtc_input_hook_api_input_hook_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['InputData'];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['HTTPValidationError'];
                };
            };
        };
    };
    offer_api_webrtc_offer_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['Body'];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['HTTPValidationError'];
                };
            };
        };
    };
    handle_incoming_call_api_telephone_incoming_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': unknown;
                };
            };
        };
    };
}
