task: DETECTION
model:
  class_path: getitune.backend.native.models.detection.yolox.YOLOX
  init_args:
    model_name: yolox_l
    label_info: 80

    optimizer:
      class_path: torch.optim.SGD
      init_args:
        lr: 0.001
        momentum: 0.9
        weight_decay: 0.0001

    scheduler:
      class_path: getitune.backend.native.schedulers.LinearWarmupSchedulerCallable
      init_args:
        num_warmup_steps: 0
        main_scheduler_callable:
          class_path: lightning.pytorch.cli.ReduceLROnPlateau
          init_args:
            mode: max
            factor: 0.1
            patience: 4
            monitor: val/map_50

engine:
  device: auto

callback_monitor: val/map_50

data: ../_base_/data/detection.yaml

callbacks:
  - class_path: getitune.backend.native.callbacks.adaptive_early_stopping.EarlyStoppingWithWarmup
    init_args:
      mode: max
      patience: 10
      check_on_train_epoch_end: false
      monitor: val/map_50
      min_delta: 0.001
      warmup_iters: 30
      warmup_epochs: 3
  - class_path: lightning.pytorch.callbacks.ModelCheckpoint
    init_args:
      dirpath: "" # use engine.work_dir
      monitor: val/map_50
      mode: max
      save_top_k: 1
      save_last: true
      auto_insert_metric_name: false
      filename: "checkpoints/epoch_{epoch:03d}"

overrides:
  gradient_clip_val: 35.0
  data:
    input_size:
      - 640
      - 640
    train_subset:
      batch_size: 8
      augmentations_cpu:
        - class_path: getitune.data.augmentation.transforms.CachedMosaic
          init_args:
            random_pop: false
            max_cached_images: 20
            img_scale: $(input_size)
        - class_path: torchvision.transforms.v2.RandomResizedCrop
          init_args:
            size: $(input_size)
            scale: [0.25, 1.0]
            ratio: [0.75, 1.333]
            antialias: true
        - class_path: torchvision.transforms.v2.SanitizeBoundingBoxes
          init_args:
            min_size: 1
        - class_path: getitune.data.augmentation.transforms.CachedMixUp
          init_args:
            img_scale: $(input_size)
            alpha: 1.5
            p: 0.5
            random_pop: false
            max_cached_images: 10
      augmentations_gpu:
        - class_path: kornia.augmentation.ColorJiggle
          init_args:
            brightness: 0.125
            contrast: 0.5
            saturation: 0.5
            hue: 0.05
            p: 0.5
        - class_path: kornia.augmentation.RandomHorizontalFlip
          init_args:
            p: 0.5
        - class_path: kornia.augmentation.RandomAffine
          init_args:
            degrees: 10.0
            translate: [0.1, 0.1]
            scale: [1.0, 1.0]
            shear: [-2.0, 2.0]
            p: 0.7
      sampler:
        class_path: getitune.data.samplers.balanced_sampler.BalancedSampler

    val_subset:
      batch_size: 8
      augmentations_cpu:
        - class_path: getitune.data.augmentation.transforms.Resize
          init_args:
            size: $(input_size)
            keep_aspect_ratio: true
            resize_targets: false
      augmentations_gpu: []
    test_subset:
      batch_size: 8
      augmentations_cpu:
        - class_path: getitune.data.augmentation.transforms.Resize
          init_args:
            size: $(input_size)
            keep_aspect_ratio: true
            resize_targets: false
      augmentations_gpu: []
