backend: ultralytics
task: DETECTION

model:
  class_path: getitune.backend.ultralytics.models.detection.UltralyticsDetectionModel
  init_args:
    model_name: yolo26s.pt
    pretrained: true
    imgsz: 640

engine:
  device: auto

training:
  epochs: 100
  batch: 16
  optimizer: auto
  lr0: 0.01
  lrf: 0.01
  momentum: 0.937
  weight_decay: 0.0005
  warmup_epochs: 3.0
  box: 7.5
  cls: 0.5
  dfl: 1.5
  patience: 100
  close_mosaic: 0

export:
  format: OPENVINO
  precision: FP32

data: ../_base_/data/detection.yaml

overrides:
  data:
    input_size:
      - 640
      - 640
    train_subset:
      batch_size: 16
      augmentations_gpu: []
      sampler:
        class_path: getitune.data.samplers.balanced_sampler.BalancedSampler
    val_subset:
      batch_size: 16
      augmentations_gpu: []
      sampler:
        class_path: torch.utils.data.SequentialSampler
    test_subset:
      batch_size: 16
      augmentations_gpu: []
      sampler:
        class_path: torch.utils.data.SequentialSampler
