import time
from abc import ABCMeta, abstractmethod

import numpy as np
from model_api.models.result import Result

from app.schemas.configuration import OutputConfig


class DispatchError(Exception):
    """Exception raised when there is an error in dispatching."""

    def __init__(self):
        super().__init__("Failed to dispatch the output")


class BaseDispatcher(metaclass=ABCMeta):
    """
    Base class for dispatchers.
    This class should be inherited by all dispatcher classes.
    """

    def __init__(self, output_config: OutputConfig) -> None:
        """
        Initialize the dispatcher.
        Args:
            output_config: Configuration for the output destination
        """
        self.output_formats = output_config.output_formats
        self.rate_limit = output_config.rate_limit
        self.min_interval = 1.0 / self.rate_limit if self.rate_limit is not None else 0.0
        self.last_dispatch_time = 0.0

    @abstractmethod
    def _dispatch(
        self,
        original_image: np.ndarray,
        image_with_visualization: np.ndarray,
        predictions: Result,
    ) -> None:
        """
        Internal method to dispatch an image with predictions.

        This method should be overridden by subclasses to implement specific dispatch logic.
        Args:
            original_image (np.ndarray): The original image
            image_with_visualization (np.ndarray): The image with overlaid predictions
            predictions (Result): Predictions generated by the model
        """

    def dispatch(
        self,
        original_image: np.ndarray,
        image_with_visualization: np.ndarray,
        predictions: Result,
    ) -> None:
        """
        Dispatch an image with predictions.
        Args:
            original_image (np.ndarray): The original image
            image_with_visualization (np.ndarray): The image with overlaid predictions
            predictions (Result): Predictions generated by the model

        Raises:
            DispatchError: If there is an error in dispatching the output
        """
        # Apply rate limiting
        if self.rate_limit is not None:
            current_time = time.time()
            time_since_last = current_time - self.last_dispatch_time
            if time_since_last < self.min_interval:
                return
            self.last_dispatch_time = time.time()

        try:
            self._dispatch(original_image, image_with_visualization, predictions)
        except Exception as e:
            raise DispatchError from e
