"""schema

Revision ID: 1127bd7a7649
Revises:
Create Date: 2026-01-19 17:06:35.524887

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1127bd7a7649"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("task_type", sa.String(length=50), nullable=False),
        sa.Column("exclusive_labels", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_projects_name", "projects", ["name"], unique=False)
    op.create_table(
        "sinks",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("sink_type", sa.String(length=50), nullable=False),
        sa.Column("rate_limit", sa.Float(), nullable=True),
        sa.Column("config_data", sa.JSON(), nullable=False),
        sa.Column("output_formats", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "sources",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("source_type", sa.String(length=50), nullable=False),
        sa.Column("config_data", sa.JSON(), nullable=False),
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "dataset_revisions",
        sa.Column("project_id", sa.Text(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("files_deleted", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_dataset_revisions_project", "dataset_revisions", ["project_id"], unique=False)
    op.create_table(
        "labels",
        sa.Column("project_id", sa.Text(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("color", sa.String(length=7), nullable=False),
        sa.Column("hotkey", sa.String(length=10), nullable=True),
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "hotkey", name="uq_project_label_hotkey"),
        sa.UniqueConstraint("project_id", "name", name="uq_project_label_name"),
    )
    op.create_table(
        "training_configurations",
        sa.Column("project_id", sa.Text(), nullable=False),
        sa.Column("model_architecture_id", sa.String(length=255), nullable=True),
        sa.Column("configuration_data", sa.JSON(), nullable=False),
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "model_architecture_id", name="uq_project_model_config"),
    )
    op.create_table(
        "model_revisions",
        sa.Column("project_id", sa.Text(), nullable=False),
        sa.Column("architecture", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("parent_revision", sa.Text(), nullable=True),
        sa.Column("training_status", sa.String(length=50), nullable=False),
        sa.Column("training_configuration", sa.JSON(), nullable=False),
        sa.Column("training_dataset_id", sa.Text(), nullable=True),
        sa.Column("label_schema_revision", sa.JSON(), nullable=False),
        sa.Column("training_started_at", sa.DateTime(), nullable=True),
        sa.Column("training_finished_at", sa.DateTime(), nullable=True),
        sa.Column("files_deleted", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.ForeignKeyConstraint(["parent_revision"], ["model_revisions.id"]),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["training_dataset_id"], ["dataset_revisions.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_model_revisions_architecture", "model_revisions", ["project_id", "architecture"], unique=False)
    op.create_index(
        "idx_model_revisions_project_status", "model_revisions", ["project_id", "training_status"], unique=False
    )
    op.create_table(
        "dataset_items",
        sa.Column("project_id", sa.Text(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("format", sa.String(length=50), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("annotation_data", sa.JSON(), nullable=True),
        sa.Column("user_reviewed", sa.Boolean(), nullable=False),
        sa.Column("prediction_model_id", sa.Text(), nullable=True),
        sa.Column("source_id", sa.Text(), nullable=True),
        sa.Column("subset", sa.String(length=20), nullable=False),
        sa.Column("subset_assigned_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.ForeignKeyConstraint(["prediction_model_id"], ["model_revisions.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_dataset_items_user_reviewed", "dataset_items", ["project_id", "user_reviewed"], unique=False)
    op.create_table(
        "evaluations",
        sa.Column("model_revision_id", sa.Text(), nullable=False),
        sa.Column("dataset_revision_id", sa.Text(), nullable=False),
        sa.Column("subset", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.ForeignKeyConstraint(["dataset_revision_id"], ["dataset_revisions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["model_revision_id"], ["model_revisions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pipelines",
        sa.Column("project_id", sa.Text(), nullable=False),
        sa.Column("source_id", sa.Text(), nullable=True),
        sa.Column("sink_id", sa.Text(), nullable=True),
        sa.Column("model_revision_id", sa.Text(), nullable=True),
        sa.Column("is_running", sa.Boolean(), nullable=False),
        sa.Column("data_collection", sa.JSON(), nullable=False),
        sa.Column("device", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.ForeignKeyConstraint(["model_revision_id"], ["model_revisions.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["sink_id"], ["sinks.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("project_id"),
    )
    op.create_index("idx_pipelines_is_running", "pipelines", ["is_running"], unique=False)
    op.create_table(
        "dataset_items_labels",
        sa.Column("dataset_item_id", sa.Text(), nullable=False),
        sa.Column("label_id", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.ForeignKeyConstraint(["dataset_item_id"], ["dataset_items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["label_id"], ["labels.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("dataset_item_id", "label_id"),
    )
    op.create_table(
        "metric_scores",
        sa.Column("evaluation_id", sa.Text(), nullable=False),
        sa.Column("metric", sa.String(length=255), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.ForeignKeyConstraint(["evaluation_id"], ["evaluations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("metric_scores")
    op.drop_table("dataset_items_labels")
    op.drop_index("idx_pipelines_is_running", table_name="pipelines")
    op.drop_table("pipelines")
    op.drop_table("evaluations")
    op.drop_index("idx_dataset_items_user_reviewed", table_name="dataset_items")
    op.drop_table("dataset_items")
    op.drop_index("idx_model_revisions_project_status", table_name="model_revisions")
    op.drop_index("idx_model_revisions_architecture", table_name="model_revisions")
    op.drop_table("model_revisions")
    op.drop_table("training_configurations")
    op.drop_table("labels")
    op.drop_index("idx_dataset_revisions_project", table_name="dataset_revisions")
    op.drop_table("dataset_revisions")
    op.drop_table("sources")
    op.drop_table("sinks")
    op.drop_index("idx_projects_name", table_name="projects")
    op.drop_table("projects")
    # ### end Alembic commands ###
