task: INSTANCE_SEGMENTATION
model:
  class_path: getitune.backend.lightning.models.instance_segmentation.rtmdet_inst.RTMDetInst
  init_args:
    label_info: 80
    model_name: rtmdet_inst_tiny

    optimizer:
      class_path: torch.optim.AdamW
      init_args:
        lr: 0.004
        weight_decay: 0.01
        betas: [0.9, 0.999]

    scheduler:
      class_path: getitune.backend.lightning.schedulers.LinearWarmupSchedulerCallable
      init_args:
        num_warmup_steps: 20
        main_scheduler_callable:
          class_path: lightning.pytorch.cli.ReduceLROnPlateau
          init_args:
            mode: max
            factor: 0.1
            patience: 9
            monitor: val/map_50
            min_lr: 4e-06

engine:
  device: auto

callback_monitor: val/map_50

data: ../_base_/data/instance_segmentation.yaml

callbacks:
  - class_path: getitune.backend.lightning.callbacks.adaptive_early_stopping.EarlyStoppingWithWarmup
    init_args:
      mode: max
      patience: 10
      check_on_train_epoch_end: false
      min_delta: 0.001
      warmup_iters: 30
      warmup_epochs: 3
  - class_path: lightning.pytorch.callbacks.ModelCheckpoint
    init_args:
      dirpath: "" # use engine.work_dir
      monitor: val/map_50
      mode: max
      save_top_k: 1
      save_last: true
      auto_insert_metric_name: false
      filename: "checkpoints/epoch_{epoch:03d}"

overrides:
  reset:
    - data.train_subset.augmentations_cpu
    - data.val_subset.augmentations_cpu
    - data.test_subset.augmentations_cpu
  precision: 16-mixed
  max_epochs: 100
  gradient_clip_val: 35.0

  data:
    input_size:
      - 512
      - 512

    tile_config:
      enable_tiler: true
      enable_adaptive_tiling: true

    train_subset:
      batch_size: 8
      num_workers: 8
      augmentations_cpu:
        - class_path: getitune.data.augmentation.transforms.Resize
          init_args:
            size: $(input_size)
            keep_aspect_ratio: true
            pad_value: 114
        - class_path: torchvision.transforms.v2.RandomHorizontalFlip
          init_args:
            p: 0.5
        - class_path: torchvision.transforms.v2.Normalize
          init_args:
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
      augmentations_gpu: []
    val_subset:
      num_workers: 4
      augmentations_cpu:
        - class_path: getitune.data.augmentation.transforms.Resize
          init_args:
            size: $(input_size)
            keep_aspect_ratio: true
            pad_value: 114
            resize_targets: false
        - class_path: torchvision.transforms.v2.Normalize
          init_args:
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
      augmentations_gpu: []
    test_subset:
      num_workers: 4
      augmentations_cpu:
        - class_path: getitune.data.augmentation.transforms.Resize
          init_args:
            size: $(input_size)
            keep_aspect_ratio: true
            pad_value: 114
            resize_targets: false
        - class_path: torchvision.transforms.v2.Normalize
          init_args:
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
      augmentations_gpu: []
