id: instance-segmentation-edgecrafter-s
name: ECSeg-S

pretrained_weights:
  url: https://github.com/capsule2077/edgecrafter/releases/download/edgecrafterv1/ecseg_s.pth
  mirror_url: https://huggingface.co/Intellindust/ECSeg_S/resolve/main/model.safetensors
  sha_sum: b83b07d71b942c6255aaad1cf1f92eee075c5a548624d27464c987cd618d5a93

description: "EdgeCrafter instance segmentation model (ECSeg-S) extends ECDet with a mask prediction head for high-accuracy real-time instance segmentation."

stats:
  gigaflops: 33.0
  trainable_parameters: 10.0
  benchmark_metrics:
    coco_map_50_95: 43.0

capabilities:
  tiling: false

hyperparameters:
  training:
    learning_rate: 0.0004
    weight_decay: 0.0001
    early_stopping:
      patience: 15
    scheduler:
      factor: 0.1
      patience: 10
    gradient_clip:
      enable: true
      max_grad_norm: 0.1
    allowed_values_input_size:
      - 320
      - 448
      - 512
      - 576
      - 640
      - 704
      - 768
      - 896
    input_size_width: 512
    input_size_height: 512
  dataset_preparation:
    augmentation:
      random_zoom_out:
        enable: true
        fill: 0
        side_range:
          - 1.0
          - 4.0
        probability: 0.5
      iou_random_crop:
        enable: true
        probability: 1.0
        min_scale: 0.3
        max_scale: 1.0
