id: instance-segmentation-yolo26-n
name: YOLO26-N-Seg

pretrained_weights:
  url: https://github.com/ultralytics/assets/releases/download/v8.4.0/yolo26n-seg.pt
  mirror_url: https://github.com/ultralytics/assets/releases/download/v8.4.0/yolo26n-seg.pt
  sha_sum: "361fbfabab285c3237700b6bb91d7ecfa602cd945fffda8dbe1242829b71e73f"

description: "YOLO26-N-Seg is the nano Ultralytics YOLO26 instance segmentation model. It is optimized for fast fine-tuning and low-latency inference while using the Geti Tune data pipeline for preprocessing and dataset handling."
stats:
  gigaflops: 9.1
  trainable_parameters: 2.7
  benchmark_metrics:
    coco_map_50_95: 33.9

capabilities:
  tiling: false

hyperparameters:
  training:
    learning_rate: 0.01
    weight_decay: 0.0005
    batch_size: 16
    input_size_width: 640
    input_size_height: 640
    allowed_values_input_size:
      - 640
  dataset_preparation:
    augmentation:
      tiling:
        enable: false
      random_horizontal_flip:
        enable: true
        probability: 0.5
      iou_random_crop:
        enable: true
