callback_monitor: val/Dice

data: ../_base_/data/semantic_segmentation.yaml
overrides:
  reset:
    - data.train_subset.augmentations_cpu
    - data.train_subset.augmentations_gpu
    - data.val_subset.augmentations_cpu
    - data.test_subset.augmentations_cpu

  data:
    stack_images: false
    train_subset:
      augmentations_cpu:
        - class_path: torchvision.transforms.v2.ToImage
    val_subset:
      augmentations_cpu:
        - class_path: torchvision.transforms.v2.ToImage
    test_subset:
      batch_size: 64
      num_workers: 4
      augmentations_cpu:
        - class_path: torchvision.transforms.v2.ToImage
