callback_monitor: val/accuracy

data: ../../_base_/data/classification.yaml

overrides:
  reset:
    - data.train_subset.augmentations_cpu
    - data.train_subset.augmentations_gpu
    - data.val_subset.augmentations_cpu
    - data.test_subset.augmentations_cpu

  data:
    task: MULTI_LABEL_CLS
    train_subset:
      augmentations_cpu:
        - class_path: otx.data.augmentation.transforms.Resize
          init_args:
            size: $(input_size)
            keep_aspect_ratio: false
      augmentations_gpu: []
    test_subset:
      batch_size: 128
      augmentations_cpu:
        - class_path: otx.data.augmentation.transforms.Resize
          init_args:
            size: $(input_size)
            keep_aspect_ratio: false
      augmentations_gpu: []
