x-proxies: &proxies
  args:
    - HTTP_PROXY=${HTTP_PROXY}
    - HTTPS_PROXY=${HTTPS_PROXY}
    - NO_PROXY=${NO_PROXY}
    - http_proxy=${http_proxy}
    - https_proxy=${https_proxy}
    - no_proxy=${no_proxy}

services:
  server:
    image: geti-tune:${TAG:-latest}
    restart: unless-stopped
    build:
      context: ..
      dockerfile: docker/Dockerfile
      <<: *proxies
    working_dir: /app
    volumes:
      - ../backend/data/:/app/data/
    ports:
      - "80:80"
