model:
  class_path: otx.algo.detection.deim.DEIMDFine
  init_args:
    model_name: deim_dfine_hgnetv2_x
    label_info: 80
    multi_scale: true

    optimizer:
      class_path: torch.optim.AdamW
      init_args:
        lr: 0.0005
        betas: [0.9, 0.999]
        weight_decay: 0.000125

    scheduler:
      class_path: otx.core.schedulers.LinearWarmupSchedulerCallable
      init_args:
        num_warmup_steps: 100
        main_scheduler_callable:
          class_path: lightning.pytorch.cli.ReduceLROnPlateau
          init_args:
            mode: max
            factor: 0.1
            patience: 6
            monitor: val/map_50
engine:
  task: DETECTION
  device: auto

callback_monitor: val/map_50

data_aug_switch:
  class_path: otx.algo.callbacks.aug_scheduler.DataAugSwitch
  init_args:
    policy_epochs: [4, 29, 50]
    policies:
      no_aug:
        to_tv_image: false
        transforms:
          - class_path: otx.core.data.transform_libs.torchvision.Resize
            init_args:
              scale: [640, 640]
              keep_ratio: false
              is_numpy_to_tvtensor: true
          - class_path: torchvision.transforms.v2.ToDtype
            init_args:
              dtype: ${as_torch_dtype:torch.float32}
              scale: false
          - class_path: torchvision.transforms.v2.Normalize
            init_args:
              mean: [0.0, 0.0, 0.0]
              std: [255.0, 255.0, 255.0]

      light_aug:
        to_tv_image: true
        transforms:
          - class_path: torchvision.transforms.v2.ToImage
          - class_path: torchvision.transforms.v2.RandomPhotometricDistort
            init_args:
              p: 0.5
          - class_path: otx.core.data.transform_libs.torchvision.RandomFlip
            init_args:
              prob: 0.5
          - class_path: otx.core.data.transform_libs.torchvision.Resize
            init_args:
              scale: [640, 640]
              transform_bbox: true
              keep_ratio: false
              is_numpy_to_tvtensor: true
          - class_path: torchvision.transforms.v2.ToDtype
            init_args:
              dtype: ${as_torch_dtype:torch.float32}
              scale: false
          - class_path: torchvision.transforms.v2.Normalize
            init_args:
              mean: [0.0, 0.0, 0.0]
              std: [255.0, 255.0, 255.0]

      strong_aug_1:
        to_tv_image: false
        transforms:
          - class_path: otx.core.data.transform_libs.torchvision.CachedMosaic
            init_args:
              random_pop: false
              max_cached_images: 20
              img_scale: [640, 640]
          - class_path: otx.core.data.transform_libs.torchvision.RandomAffine
            init_args:
              scaling_ratio_range:
                - 0.1
                - 2.0
              border: [-320, -320]
          - class_path: otx.core.data.transform_libs.torchvision.CachedMixUp
            init_args:
              img_scale: [640, 640] # (H, W)
              ratio_range:
                - 1.0
                - 1.0
              prob: 0.5
              random_pop: false
              max_cached_images: 10
          - class_path: otx.core.data.transform_libs.torchvision.Resize
            init_args:
              scale: [640, 640] # (H, W)
              keep_ratio: false
              transform_bbox: true
          - class_path: otx.core.data.transform_libs.torchvision.YOLOXHSVRandomAug
          - class_path: otx.core.data.transform_libs.torchvision.RandomFlip
            init_args:
              prob: 0.5
              is_numpy_to_tvtensor: true
          - class_path: torchvision.transforms.v2.ToDtype
            init_args:
              dtype: ${as_torch_dtype:torch.float32}
              scale: false
          - class_path: torchvision.transforms.v2.Normalize
            init_args:
              mean: [0.0, 0.0, 0.0]
              std: [255.0, 255.0, 255.0]

      strong_aug_2:
        to_tv_image: true
        transforms:
          - class_path: torchvision.transforms.v2.ToImage
          - class_path: torchvision.transforms.v2.RandomPhotometricDistort
            init_args:
              p: 0.5
          - class_path: torchvision.transforms.v2.RandomZoomOut # Can't be used when using CachedMosaic
            init_args:
              fill: 0
          - class_path: otx.core.data.transform_libs.torchvision.RandomIoUCrop # Can't be used when using CachedMosaic
            init_args:
              p: 0.8
          - class_path: torchvision.transforms.v2.SanitizeBoundingBoxes
            init_args:
              min_size: 1
          - class_path: otx.core.data.transform_libs.torchvision.RandomFlip
            init_args:
              prob: 0.5
          - class_path: otx.core.data.transform_libs.torchvision.Resize
            init_args:
              scale: [640, 640]
              transform_bbox: true
              keep_ratio: false
              is_numpy_to_tvtensor: true
          - class_path: torchvision.transforms.v2.ToDtype
            init_args:
              dtype: ${as_torch_dtype:torch.float32}
              scale: false
          - class_path: torchvision.transforms.v2.Normalize
            init_args:
              mean: [0.0, 0.0, 0.0]
              std: [255.0, 255.0, 255.0]

data: ../_base_/data/torchvision_base.yaml
overrides:
  callbacks:
    - class_path: otx.algo.callbacks.adaptive_train_scheduling.AdaptiveTrainScheduling
      init_args:
        max_interval: 1
        min_lrschedule_patience: 3
    - class_path: otx.algo.callbacks.adaptive_early_stopping.EarlyStoppingWithWarmup
      init_args:
        warmup_iters: 100
        warmup_epochs: 7
    - class_path: otx.algo.callbacks.aug_scheduler.AugmentationSchedulerCallback

  data:
    input_size:
      - 640
      - 640
    task: DETECTION
    data_format: coco_instances
    train_subset:
      batch_size: 8
      num_workers: 4
      transforms:
        - class_path: otx.core.data.transform_libs.torchvision.Resize
          init_args:
            scale: $(input_size)
            keep_ratio: false
            is_numpy_to_tvtensor: true
        - class_path: torchvision.transforms.v2.ToDtype
          init_args:
            dtype: ${as_torch_dtype:torch.float32}
            scale: false
        - class_path: torchvision.transforms.v2.Normalize
          init_args:
            mean: [0.0, 0.0, 0.0]
            std: [255.0, 255.0, 255.0]
      sampler:
        class_path: otx.algo.samplers.balanced_sampler.BalancedSampler

    val_subset:
      batch_size: 8
      transforms:
        - class_path: otx.core.data.transform_libs.torchvision.Resize
          init_args:
            scale: $(input_size)
            keep_ratio: false
            is_numpy_to_tvtensor: true
        - class_path: torchvision.transforms.v2.ToDtype
          init_args:
            dtype: ${as_torch_dtype:torch.float32}
            scale: false
        - class_path: torchvision.transforms.v2.Normalize
          init_args:
            mean: [0.0, 0.0, 0.0]
            std: [255.0, 255.0, 255.0]

    test_subset:
      batch_size: 8
      transforms:
        - class_path: otx.core.data.transform_libs.torchvision.Resize
          init_args:
            scale: $(input_size)
            keep_ratio: false
            is_numpy_to_tvtensor: true
        - class_path: torchvision.transforms.v2.ToDtype
          init_args:
            dtype: ${as_torch_dtype:torch.float32}
            scale: false
        - class_path: torchvision.transforms.v2.Normalize
          init_args:
            mean: [0.0, 0.0, 0.0]
            std: [255.0, 255.0, 255.0]
