default_language_version:
  python: python3.10 # Should match the lowest Python version supported by the library (set in library/pyproject.toml)

repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: "0.9.27"
    hooks:
      - id: uv-lock
        name: uv lock
        always_run: true
        pass_filenames: false

  - repo: local
    hooks:
      - id: pyrefly-check
        name: pyrefly-check
        entry: uv run pyrefly check --baseline=pyrefly-baseline.json
        pass_filenames: false
        language: system
