callback_monitor: val/accuracy

data: ../../_base_/data/torchvision_base.yaml

overrides:
  data:
    task: MULTI_CLASS_CLS
    train_subset:
      augmentations_cpu:
        - class_path: otx.data.augmentation.transforms.Resize
          init_args:
            size: $(input_size)
            keep_aspect_ratio: false
      augmentations_gpu: []
    test_subset:
      batch_size: 128
      augmentations_cpu:
        - class_path: otx.data.augmentation.transforms.Resize
          init_args:
            size: $(input_size)
            keep_aspect_ratio: false
      augmentations_gpu: []
