# Copyright (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

"""Convert a COCO-format detection dataset to Ultralytics YOLO format.

Usage:
    python scripts/convert_coco_to_yolo.py \
        --src /home/kprokofi/bench_data/detection/wgisd_merged_coco_small \
        --dst /home/kprokofi/bench_data/detection/wgisd_yolo
"""

from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path


def convert_split(
    ann_file: Path,
    src_images_dir: Path,
    dst_images_dir: Path,
    dst_labels_dir: Path,
    cat_id_to_idx: dict[int, int],
) -> int:
    """Convert one split (train/val/test) from COCO to YOLO format.

    Returns:
        Number of images processed.
    """
    with open(ann_file) as f:
        coco = json.load(f)

    # Build image_id -> image info lookup
    id_to_img = {img["id"]: img for img in coco["images"]}

    # Group annotations by image_id
    img_to_anns: dict[int, list[dict]] = {}
    for ann in coco["annotations"]:
        img_to_anns.setdefault(ann["image_id"], []).append(ann)

    dst_images_dir.mkdir(parents=True, exist_ok=True)
    dst_labels_dir.mkdir(parents=True, exist_ok=True)

    for img_info in coco["images"]:
        img_id = img_info["id"]
        file_name = img_info["file_name"]
        w, h = img_info["width"], img_info["height"]

        # Copy image
        src_path = src_images_dir / file_name
        dst_path = dst_images_dir / file_name
        if not dst_path.exists():
            shutil.copy2(src_path, dst_path)

        # Write YOLO label file
        stem = Path(file_name).stem
        label_path = dst_labels_dir / f"{stem}.txt"
        lines = []
        for ann in img_to_anns.get(img_id, []):
            if ann.get("iscrowd", 0):
                continue
            cls_idx = cat_id_to_idx[ann["category_id"]]
            # COCO bbox is [x_min, y_min, width, height] in pixels
            bx, by, bw, bh = ann["bbox"]
            # Convert to YOLO: x_center, y_center, width, height (normalized)
            x_center = (bx + bw / 2) / w
            y_center = (by + bh / 2) / h
            nw = bw / w
            nh = bh / h
            lines.append(f"{cls_idx} {x_center:.6f} {y_center:.6f} {nw:.6f} {nh:.6f}")

        label_path.write_text("\n".join(lines) + "\n" if lines else "")

    return len(coco["images"])


def main() -> None:
    parser = argparse.ArgumentParser(description="Convert COCO dataset to YOLO format")
    parser.add_argument("--src", type=Path, required=True, help="Source COCO dataset root")
    parser.add_argument("--dst", type=Path, required=True, help="Destination YOLO dataset root")
    args = parser.parse_args()

    src: Path = args.src
    dst: Path = args.dst

    # Read categories from train annotation
    train_ann = src / "annotations" / "instances_train.json"
    with open(train_ann) as f:
        coco = json.load(f)

    categories = sorted(coco["categories"], key=lambda c: c["id"])
    cat_id_to_idx = {cat["id"]: idx for idx, cat in enumerate(categories)}
    names = {idx: cat["name"] for idx, cat in enumerate(categories)}

    print(f"Categories ({len(categories)}): {names}")
    print(f"Category ID mapping (COCO -> YOLO): {cat_id_to_idx}")

    # Convert each split
    for split in ("train", "val", "test"):
        ann_file = src / "annotations" / f"instances_{split}.json"
        if not ann_file.exists():
            print(f"  Skipping {split} (no annotation file)")
            continue

        n = convert_split(
            ann_file=ann_file,
            src_images_dir=src / "images" / split,
            dst_images_dir=dst / "images" / split,
            dst_labels_dir=dst / "labels" / split,
            cat_id_to_idx=cat_id_to_idx,
        )
        print(f"  {split}: {n} images")

    # Write dataset.yaml
    yaml_content = f"""\
# WGISD (Wine Grape Image Segmentation Dataset) - YOLO format
# Auto-generated by convert_coco_to_yolo.py

path: {dst.resolve()}
train: images/train
val: images/val
test: images/test

names:
"""
    for idx, name in names.items():
        yaml_content += f"  {idx}: {name}\n"

    yaml_path = dst / "dataset.yaml"
    yaml_path.write_text(yaml_content)
    print(f"\nDataset YAML written to: {yaml_path}")
    print("Done.")


if __name__ == "__main__":
    main()
