name: "Bandit scan"

on: pull_request

permissions: {}

jobs:
  bandit-scan:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - id: files
        uses: tj-actions/changed-files@239aef84a5502c79a1cea96e495d17588c66c659 # v45.0.7
        with:
          files: |
            **/*.py
            **/*.pyx
            **/*.pyi
      - name: Setup Python
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: "3.12"

      - name: Run checks
        run: |
          CHANGED_FILES="${{steps.files.outputs.all_changed_files}}"
          if [[ ! -z $CHANGED_FILES ]]; then
            pip install bandit
            echo "Bandit version: "$(bandit --version | head -1)
            echo "The files will be checked: "$(echo $CHANGED_FILES)
            bandit -a file -r -c .ci/ipas_default.config $CHANGED_FILES
          else
            echo "No files with the \"py\" extension found"
          fi
