# This workflow is purely for validating the docs build.
name: Build Docs Validation

on:
  workflow_dispatch: # run on request (no need for PR)
  pull_request:
    paths:
      - "docs/**"
      - "src/**"
      - "pyproject.toml"
      - ".readthedocs.yaml"

# Declare default permissions as read only.
permissions: read-all

jobs:
  Build-Docs:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: "3.12"
      - name: Install tox
        run: |
          pip install '.[ci_tox]'
      - name: Build-Docs
        run: tox -e build-doc
      - name: Check docs build
        run: |
          echo "Documentation built successfully!"
          echo "Check docs/build/html/index.html for local preview"
