name: Geti Tune Library checks

on:
  push:
    branches:
      - develop
      - release/**
    tags:
      - "v*"
  pull_request:
  merge_group:
    branches:
      - develop
      - release/**
  workflow_dispatch: # run on request (no need for PR)

permissions: {} # No permissions by default

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.after }}
  cancel-in-progress: true

jobs:
  # Determines if workflow should execute based on event type and changed paths
  # If push or workflow_dispatch -> always run
  # If PR or merge_group -> run only if files in specified paths changed
  check_paths:
    name: Check if workflow should run
    runs-on: ubuntu-latest
    outputs:
      run_workflow: ${{ steps.run_workflow.outputs.run }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Get all paths that should trigger the workflow
        id: changed-files-yaml
        uses: tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62 # v47.0.0
        with:
          files_yaml: |
            test:
              - library/**
              - .github/**

      - name: Set run flag
        id: run_workflow
        run: |
          if [ "${{ github.event_name }}" = "push" ] || [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "run=true" >> "$GITHUB_OUTPUT"
          elif [ "${{ steps.changed-files-yaml.outputs.test_any_changed }}" = "true" ]; then
            echo "run=true" >> "$GITHUB_OUTPUT"
          else
            echo "run=false" >> "$GITHUB_OUTPUT"
          fi

  Code-Quality-Checks:
    runs-on: ubuntu-24.04
    needs: check_paths
    if: needs.check_paths.outputs.run_workflow == 'true'
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6.8.0
        with:
          enable-cache: false
          python-version: "3.12"
          version: "0.8.15"

      - name: Installing dependencies
        working-directory: library
        run: uv sync --locked --extra dev --extra cuda --no-extra xpu

      - name: Run pre-commit checks
        working-directory: library
        run: uv run --frozen --extra dev --extra cuda --no-extra xpu pre-commit run --all-files

  Unit-Test:
    runs-on: [self-hosted, linux, x64, dev, dmount]
    permissions:
      contents: read
      # The id-token permission is required by Codecov to use OIDC
      id-token: write
    needs:
      - Code-Quality-Checks
      - check_paths
    if: needs.check_paths.outputs.run_workflow == 'true'
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]
    name: Unit-Test-with-Python${{ matrix.python-version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6.8.0
        with:
          enable-cache: false
          python-version: ${{ matrix.python-version }}
          version: "0.8.15"

      - name: Installing dependencies
        working-directory: library
        run: |
          uv lock --check
          uv sync --frozen --extra test

      - name: Unit testing
        working-directory: library
        run: uv run pytest tests/unit --cov --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5.5.1
        with:
          directory: library
          flags: coverage_unit-test_Python-${{ matrix.python-version }}
          use_oidc: true

  Integration-Test:
    #if: |
    #  github.event.pull_request.draft == false &&
    #  !(startsWith(github.event.pull_request.title, '[WIP]')) &&
    #  needs.check_paths.outputs.run_workflow == 'true'
    runs-on: [self-hosted, linux, x64, dev, dmount]
    permissions:
      contents: read
    needs:
      - Unit-Test
      - check_paths
    strategy:
      fail-fast: false
      matrix:
        include:
          - task: "multi_class_cls"
            python-version: "3.12"
          - task: "multi_label_cls"
            python-version: "3.12"
          - task: "h_label_cls"
            python-version: "3.12"
          - task: "anomaly"
            python-version: "3.12"
          - task: "keypoint_detection"
            python-version: "3.12"
          - task: "detection"
            python-version: "3.12"
          - task: "instance_segmentation"
            python-version: "3.12"
          - task: "semantic_segmentation"
            python-version: "3.12"
    name: Integration-Test-${{ matrix.task }}-py312
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6.8.0
        with:
          enable-cache: false
          python-version: ${{ matrix.python-version }}
          version: "0.8.15"

      - name: Installing dependencies
        working-directory: library
        run: |
          uv lock --check
          uv sync --frozen --extra cuda --extra test

      - name: Integration testing
        working-directory: library
        env:
          CUBLAS_WORKSPACE_CONFIG: ":4096:8"
        run: uv run --frozen --extra cuda --extra test pytest tests/integration -ra --showlocals --csv=${{ matrix.task }}_Python-${{ matrix.python-version }}.csv --task ${{ matrix.task }} --open-subprocess --run-category-only

  required_check:
    name: Required Check lib-lint-and-test
    needs:
      - check_paths
      - Code-Quality-Checks
      - Unit-Test
      - Integration-Test
    runs-on: ubuntu-latest
    env:
      CHECKS: ${{ join(needs.*.result, ' ') }}
    if: always() && !cancelled()
    steps:
      - name: Check jobs results
        run: |
          for check in ${CHECKS}; do
            echo "::notice::check=${check}"
            if [[ "$check" != "success" && "$check" != "skipped" ]]; then
              echo "::error ::Required status checks failed. They must succeed before this pull request can be merged."
              exit 1
            fi
          done
