model:
  class_path: otx.algo.keypoint_detection.rtmpose.RTMPoseTiny
  init_args:
    label_info: 17
    input_size:
      - 512
      - 512

    optimizer:
      class_path: torch.optim.AdamW
      init_args:
        lr: 0.001
        weight_decay: 0.

    scheduler:
      class_path: otx.core.schedulers.LinearWarmupSchedulerCallable
      init_args:
        num_warmup_steps: 100
        main_scheduler_callable:
          class_path: torch.optim.lr_scheduler.CosineAnnealingLR
          init_args:
            T_max: 10000
            eta_min: 0

engine:
  task: KEYPOINT_DETECTION
  device: auto

callback_monitor: val/PCK

data: ../_base_/data/keypoint_detection.yaml

overrides:
  gradient_clip_val: 35.0
  reset:
    - data.train_subset.transforms
    - data.val_subset.transforms
    - data.test_subset.transforms
  data:
    input_size:
      - 512
      - 512
    train_subset:
      transforms:
        - class_path: otx.core.data.transform_libs.torchvision.TopdownAffine
          init_args:
            input_size: $(input_size)
            is_numpy_to_tvtensor: true
            affine_transforms_prob: 1.0
        - class_path: torchvision.transforms.v2.ToDtype
          init_args:
            dtype: ${as_torch_dtype:torch.float32}
        - class_path: torchvision.transforms.v2.Normalize
          init_args:
            mean: [123.675, 116.28, 103.53]
            std: [58.395, 57.12, 57.375]
    val_subset:
      transforms:
        - class_path: otx.core.data.transform_libs.torchvision.Resize
          init_args:
            scale: $(input_size)
            keep_ratio: true
            transform_keypoints: true
        - class_path: otx.core.data.transform_libs.torchvision.Pad
          init_args:
            size: $(input_size)
            pad_val: 0
            is_numpy_to_tvtensor: true
        - class_path: torchvision.transforms.v2.ToDtype
          init_args:
            dtype: ${as_torch_dtype:torch.float32}
        - class_path: torchvision.transforms.v2.Normalize
          init_args:
            mean: [123.675, 116.28, 103.53]
            std: [58.395, 57.12, 57.375]
    test_subset:
      transforms:
        - class_path: otx.core.data.transform_libs.torchvision.Resize
          init_args:
            scale: $(input_size)
            keep_ratio: true
            transform_keypoints: true
        - class_path: otx.core.data.transform_libs.torchvision.Pad
          init_args:
            size: $(input_size)
            pad_val: 0
            is_numpy_to_tvtensor: true
        - class_path: torchvision.transforms.v2.ToDtype
          init_args:
            dtype: ${as_torch_dtype:torch.float32}
        - class_path: torchvision.transforms.v2.Normalize
          init_args:
            mean: [123.675, 116.28, 103.53]
            std: [58.395, 57.12, 57.375]

  callbacks:
    - class_path: otx.algo.callbacks.adaptive_early_stopping.EarlyStoppingWithWarmup
      init_args:
        warmup_iters: 300
